version: '3'
services:
  cookiecloud:
    image: easychen/cookiecloud:latest
    build: ./docker
    restart: always
    volumes:
      - ./data:/data/api/data
    ports:
      - "${COOKIECLOUD_PORT:-8088}:8088"
